filebeat.prospectors:
- input_type: log
  document_type: xalt_log
  tags: ["xalt_log"]
  paths:
    - /var/log/xalt/*/*.json

processors:
- decode_json_fields:
    when:
        contains:
            tags: xalt_log
    fields: ["message"]
    target: ""

output.logstash:
  codec.json:
    pretty: false
  hosts: ["192.168.0.140:5044"]
