filebeat.prospectors:
- input_type: log
  document_type: xalt_log
  tags: ["xalt_log", "run"]
  paths:
    - /var/log/xalt/*/run.*.json
- input_type: log
  document_type: xalt_log
  tags: ["xalt_log", "link"]
  paths:
    - /var/log/xalt/*/link.*.json
- input_type: log
  document_type: xalt_log
  tags: ["xalt_log", "pkg"]
  paths:
    - /var/log/xalt/*/pkg.*.json

processors:
- decode_json_fields:
    when:
        contains:
            tags: xalt_log
    fields: ["message"]
    target: ""

output.logstash:
  codec.json:
    pretty: false
  hosts: ["192.168.239.172:5044"]
